services:
  backend:
    image: ${IMAGE_BACKEND}
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - ${PORT_BACKEND:-8000}:${PORT_BACKEND:-8000}
    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:15.4
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-events_db}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${PORT_POSTGRES:-5432}:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/pg/:/var/lib/postgresql/data/